# Generated by Django 3.2.3 on 2021-07-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('author_mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('publication', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libraray_dataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_books', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('staff_id', models.CharField(default='Some string', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('emp_id', models.CharField(default='SOME STRING', max_length=20, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(default='SOME STRING', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='SOME STRING', max_length=200)),
                ('email', models.EmailField(default='SOME STRING', max_length=100)),
                ('contact', models.CharField(default='SOME STRING', max_length=10)),
                ('branch', models.CharField(default='SOME STRING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('Renewal_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.student')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_borrowed_books', models.IntegerField(default=0)),
                ('no_returned_books', models.IntegerField(default=0)),
                ('no_lost_books', models.IntegerField(default=0)),
                ('fine_amount', models.IntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.student')),
            ],
        ),
    ]
