# Generated by Django 3.2.3 on 2021-07-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='staff',
        ),
    ]
