# Generated by Django 3.2.3 on 2021-07-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_borrower_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_borrowed_books', models.IntegerField(default=0)),
                ('no_returned_books', models.IntegerField(default=0)),
                ('no_lost_books', models.IntegerField(default=0)),
                ('fine_amount', models.IntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffBorrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('Renewal_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.staff')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Libraray_dataBase',
        ),
        migrations.RemoveField(
            model_name='account',
            name='staff',
        ),
    ]
