# Generated by Django 3.2.3 on 2021-08-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_usersaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersAccount',
        ),
    ]
