# Generated by Django 3.2.3 on 2021-08-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_usersaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersAccount',
        ),
    ]
