# Generated by Django 3.2.2 on 2021-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(to='appointments.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='appointment',
            field=models.ManyToManyField(to='appointments.Appointment'),
        ),
    ]
