# Generated by Django 3.2.2 on 2021-09-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
