# Generated by Django 3.2.2 on 2021-10-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20211004_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('modify_doctor', 'Modify Doctor'),)},
        ),
    ]
