# Generated by Django 3.2.8 on 2021-10-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='eachslottime',
            field=models.IntegerField(null=True),
        ),
    ]
