# Generated by Django 3.2.8 on 2021-10-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
