# Generated by Django 3.2.8 on 2021-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_delete_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
    ]
