# Generated by Django 3.2.8 on 2021-11-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_auto_20211118_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
