# Generated by Django 3.2.8 on 2021-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_alter_patient_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
