# Generated by Django 3.2.8 on 2021-11-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
