# Generated by Django 3.2.8 on 2021-11-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_alter_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
