# Generated by Django 3.2.2 on 2021-10-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20210929_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('can_delete_doctor', 'Delete Doctor'),)},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
