# Generated by Django 3.2.3 on 2021-06-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_No', models.AutoField(help_text='Unique Emp no for employee table', primary_key=True, serialize=False)),
                ('First_Name', models.CharField(help_text='Employee first name', max_length=14)),
                ('Middle_Name', models.CharField(help_text='Employee middle name', max_length=14, null=True)),
                ('Last_Name', models.CharField(help_text='Employee last name', max_length=14)),
                ('Birth_Date', models.DateField(help_text='Employee birth date')),
                ('Gender', models.CharField(help_text='Employee gender', max_length=1)),
                ('Street_Address', models.CharField(max_length=50)),
                ('Address2', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Postal_Code', models.PositiveIntegerField(default=0)),
                ('Country', models.CharField(max_length=20)),
                ('Mobile_Number', models.PositiveIntegerField(default=0)),
                ('Email_Address', models.EmailField(max_length=70)),
                ('Hire_Date', models.DateField(help_text='Employee joining date')),
                ('Designation', models.CharField(max_length=10)),
                ('Salary', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
