# Generated by Django 3.2.3 on 2021-06-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210608_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('LeaveBal_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Leave_Type', models.CharField(choices=[('Personal', 'Personal'), ('Sick', 'Sick')], max_length=10)),
                ('Available_Days', models.PositiveIntegerField(default=0, help_text='Remaining/available leave days per employee')),
                ('Allocated_Days', models.PositiveIntegerField(default=0, help_text='No of leave days allocated to a leave type per employee per year')),
                ('Emp_No_LeaveBal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmpLeaveRequest',
            fields=[
                ('EmpLeave_Req_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Emp_FullName', models.CharField(max_length=50)),
                ('Leave_Type', models.CharField(choices=[('Personal', 'Personal'), ('Sick', 'Sick')], max_length=10)),
                ('Manager_FullName', models.CharField(max_length=50)),
                ('Begin_Date', models.DateField(help_text='Leave begin date')),
                ('End_Date', models.DateField(help_text='Leave end date')),
                ('Requested_Days', models.PositiveIntegerField(default=0, help_text='Total no of requested leave days')),
                ('Leave_Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], max_length=10)),
                ('Emp_Comments', models.CharField(max_length=500, null=True)),
                ('Emp_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_ID', to='accounts.employee')),
                ('Manager_Emp_No', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Manager_Emp_No', to='accounts.employee')),
            ],
        ),
    ]
