# Generated by Django 3.2.3 on 2021-06-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210611_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
