# Generated by Django 3.2.3 on 2021-06-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_leavebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleaverequest',
            name='Begin_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleaverequest',
            name='End_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleaverequest',
            name='Leave_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleaverequest',
            name='Requested_Days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
