# Generated by Django 3.2.3 on 2021-06-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210612_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleaverequest',
            name='Manager_Emp_No',
        ),
        migrations.RemoveField(
            model_name='empleaverequest',
            name='Manager_FullName',
        ),
    ]
