# Generated by Django 3.2.3 on 2021-07-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210615_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
