# Generated by Django 3.2.3 on 2021-08-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Mobile_Number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
